services:
  portfolio:
    build: .
    container_name: portfolio
    
    restart: unless-stopped
    hostname: portfolio
    environment:
      - NODE_ENV=production
      - PORT=3003
      - HOSTNAME=0.0.0.0

networks:
  default:
    name: local
    external: true